### ISSUE TITLE
Page: Home 🏠

### ISSUE THREAD

**Issue by ArmandoShala** [ArmandoShala/FILMREEL#1]
**Baseline**
An introduction to the app is presented on the home page. This is to achieve the best possible user experience. It also explains how the app works and allows you to set game preferences, such as genre and number of players.

**Problem**
How do we execute the onboarding experience?

**Requirement**
- [ ] Create a landing page with a logo, a brief greeting and a big play button that starts the game

**Possible way of implementation / solution**
Refer Figma for a possible implementation

**Hints**
After the user clicked play, there needs to be a settings page, where one can choose genres and player count

**Comment by ArmandoShala** [comment]
**Baseline**
The user should be greeted with a nice landing page of the app

**Problem**
-

**Requirement**
Create a landing page with a logo, a brief greeting and a big play button that starts the game

**Possible way of implementation / solution**
Refer Figma for a possible implementation

**Hints**
After the user clicked play, there needs to be a settings page, where one can choose genres and player count

**Comment by landrit** [comment]
I see a problem on how the user is guided through the app. Do we want to use a short video? Tutorial? 
Or something more like intro js --> https://introjs.com/ 😜

**Comment by ArmandoShala** [comment]
> I see a problem on how the user is guided through the app. Do we want to use a short video? Tutorial?
> Or something more like intro js --> https://introjs.com/ 😜

You're right! Do you prefer something like introjs or more just like a screenshot with a button **Don't show again**? For the school project I'd go with a simple screenshot

**Comment by landrit** [comment]
I've updated the project description..
