### ISSUE TITLE
Fine tune Watchlist

### ISSUE THREAD

**Issue by ArmandoShala** [ArmandoShala/FILMREEL#18]
**Is your feature request related to a problem? Please describe.**
The current implementation of the watchlist is still a bit buggy

**Describe the solution you'd like**
Squash all the bugs

**Describe alternatives you've considered**
- Check other places on how to load thumbnails
- Make seen status work

**Additional context**
[ ] Colorize checkmarks

**Comment by omerasipi** [comment]
Could you make the watchlist object somehow accessible from outside, so that I can add movies by passing a movie object #29  . It would fulfill our needs to have a temporary watchlist.
