### ISSUE TITLE
Page: Watchlist 🎥

### ISSUE THREAD

**Issue by landrit** [ArmandoShala/FILMREEL#3]
**Baseline**
The Watchlist displays all movies that have received a right-swipe. We got this idea from popular dating apps. On the watchlist, details about these movies can be expanded and the people using them can mark whether they have already seen the movie.

**Problem**
How do you handle the performance if there are dozens of movies? Do you list all the movies? What if the users are looking for a specific movie but can't remember the name exactly and there are more than 100 movies?

**Requirement**
-[ ] List the movies and show the title, short description, year and the duration
-[ ] Store all marked movies of the user
-[ ] Mark watched movies

**Possible way of implementation / solution**
1. Load the stored data from the data base 
2. Create a list where you can add a for each of the found data and show the data in the list
3. Add Lazy Loading to handle Big Data

**Hints**
Index the data base on a specific column to get faster results

**Comment by ArmandoShala** [comment]
You mentioning a good problem with the amount of marked movies. We should implement a searchable list

**Comment by landrit** [comment]
good to see that we have the same opinion 👍🏻
