### ISSUE TITLE
Page: Leaderboard 👑

### ISSUE THREAD

**Issue by landrit** [ArmandoShala/FILMREEL#5]
**Baseline**
The leaderboard page is displayed as soon as the duel is over. The leaderboard page displays the first-placed person and the corresponding score.

**Problem**
What do you do when both players have the same amount of points? 

**Requirement**
1. Add the two buttons one that returns you to the home page as well as the one that lets you get to the watchlist.
2. Compare the achieved points of the both users and show the winner on the leaderboard 👏🏻

**Possible way of implementation / solution**
1. Sum up all points of all rounds that were played in the quiz and check which players has achieved more points. List the player with more points on the leaderboard
2. Add two buttons that redirects to the homepage and to the watchlist 

**Hints**
When both players have the same amount of points I would start an extra round "the last round" that decides who wins 🫡

**Comment by ArmandoShala** [comment]
If both players have the same amount of points, either finish in a tie or answer a golden question
